### ISSUE TITLE
Book in Forever loading state

### ISSUE THREAD

**Issue by gustavo-depaula** [farshed/duofolio#7] opened 2020-09-08 05:23 UTC
Hi! I found out about this project on Reddit and was excited to try it out, but when I load a `Le petit prince` epub sample, the book stays in a forever loading state:
![image](https://user-images.githubusercontent.com/732422/92436035-13e06a80-f17a-11ea-8a6e-811939fcb119.png)
I've tried other epub readers and it doesn't seem to be a problem with this file. I can provide the file, if it's helpful.

**Comment by farshed** [comment] 2020-09-08 05:27
Thank you for reporting. Please provide the file

**Comment by gustavo-depaula** [comment] 2020-09-08 05:34
@farshed can be downloaded here: http://library.lol/main/5C373C58FD0418A284BE93E5794FD669

**Comment by farshed** [comment] 2020-09-08 06:21
Hey Gustavo, the problem was being caused by the file's name. Fixing it now.

**Comment by farshed** [comment] 2020-09-17 13:39
Hey @gustavo-depaula, I couldn't find the exact cause of the problem. Even after fixing the issue with the filename, I can only open it partially (first 3 pages or so). Since the issue is not reproducible with any other book, I'm closing this for now.

**Closed by farshed** 2020-09-17 13:39 UTC
